### PR TITLE
Update to 1.0.49 (it's a newer build than the one currently set on master/f25/f24)

### PR DESCRIPTION
**Pull request by petersaints**
I updated the package so that it gets the 1.0.47 version from Spotify's Debian repository.

More details at: https://bugzilla.rpmfusion.org/show_bug.cgi?id=4371#c9

### CODE REVIEW

**Comment by petersaints** [comment]
I updated my fork to 1.0.49 (it's a newer build than the one currently set on master/f25/f24).
Please merge the changes into rpmfusion.

**Comment by sergiomb2** [comment]
Olá, 
warning: bogus date in %changelog: Sun Mar 13 2017 Pedro Albuquerque Santos <petersaints@gmail.com.com> - 1.0.49-2

didn't you use rpmdev-bumpspec ? 
Many thanks I will merge soon I tested .

**Comment by petersaints** [comment]
I edited manually (I'm a packaging noob) and forgot to change the day of
the week.

On Mar 14, 2017 01:08, "Sérgio Basto" <notifications@github.com> wrote:

Olá,
warning: bogus date in %changelog: Sun Mar 13 2017 Pedro Albuquerque Santos
petersaints@gmail.com.com - 1.0.49-2

didn't you use rpmdev-bumpspec ?
Many thanks I will merge soon I tested .

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rpmfusion/lpf-spotify-client/pull/3#issuecomment-286291610>,
or mute the thread

**Comment by sergiomb2** [comment]
merged ! , podes fechar o ticket :)

**Comment by sergiomb2** [comment]
Thanks for your PR.
You may consider to maintain this package directly from our infra ... http://rpmfusion.org/Contributors 
I may sponsor you .

**Comment by petersaints** [comment]
Yes. I would gladly do that. But I still need to read and understand well
how the packaging tools work on Fedora. Any more tips other than the link
you provided? If I'm able to do that I have no problems in pushing a new
package when I notice that Spotify has released a new version.

Pedro Albuquerque Santos

**Comment by kwizart** [comment]
Indeed, it's best to understand how to make package locally before to start contributing.
You can have a look here for a start
https://fedoraproject.org/wiki/How_to_create_an_RPM_package
Then
https://fedoraproject.org/wiki/Join_the_package_collection_maintainers

The infrastructure is handling the package creation process from "this" source code to the repository.

**Pull request closed without merging**
