### PR TITLE
Update to 1.2.31.1205.g4d59ad7c

### PR DESCRIPTION
**Pull request by vmaerten**
I've used your script `check_new_version.py` to do it, but I haven't the right to checkout, push and build.

As issue are not enable, I take this PR as a opportunity to ask you, can be worth it to add a github action that check if a new version is available ? (for example every day or week)
The issue is : they delete the old .deb so we cannot update if the last version is not available on this repo.
If yes, I can propose a PR to do it.

Thanks for maintaining this

### CODE REVIEW

**Comment by sergiomb2** [comment]
giithub is just an mirror which is not synced due a bug 

see : https://pkgs.rpmfusion.org/cgit/nonfree/lpf-spotify-client.git/
and https://pkgs.rpmfusion.org/cgit/nonfree/lpf-spotify-client.git/commit/?id=0cfa86da298ed607ddbeb8944e178f98e2d9c3da

**Comment by sergiomb2** [comment]
> As issue are not enable,

you have 
https://bugzilla.rpmfusion.org/enter_bug.cgi?product=Fedora&component=lpf-spotify-client

> I take this PR as a opportunity to ask you, can be worth it to add a github action that check if a new version is available ? (for example every day or week) 

we can use github action that check if a new version is available ? and do a PR , if yes I can do a fork and run it there ... 

> The issue is : they delete the old .deb so we cannot update if the last version is not available on this repo. If yes, I can propose a PR to do it.

yes, it is well known

I used to see updates when I had an Ubuntu (at work), it was my notifications :smiley: , now I check it from time to time or someone warning me in a bug report or a PR on github ...

**Comment by vmaerten** [comment]
> giithub is just an mirror which is not synced due a bug
> 
> see : [pkgs.rpmfusion.org/cgit/nonfree/lpf-spotify-client.git](https://pkgs.rpmfusion.org/cgit/nonfree/lpf-spotify-client.git/) and [pkgs.rpmfusion.org/cgit/nonfree/lpf-spotify-client.git/commit/?id=0cfa86da298ed607ddbeb8944e178f98e2d9c3da](https://pkgs.rpmfusion.org/cgit/nonfree/lpf-spotify-client.git/commit/?id=0cfa86da298ed607ddbeb8944e178f98e2d9c3da)

Oh thanks! I did not know. I'll follow this one

**Comment by vmaerten** [comment]
> we can use github action that check if a new version is available ? and do a PR , if yes I can do a fork and run it there ...

Yes ! I managed to have a Github Action running and do a PR if needed to notify you.

**Pull request closed without merging**
