### PR TITLE
Update to 1.2.25.1011.g0348bea

### PR DESCRIPTION
**Pull request by HaydenHildreth**
Please review if possible @sergiomb2

### CODE REVIEW

**Comment by HaydenHildreth** [comment]
I hope this looks good, please let me know if anything is incorrect and I can make adjustments, or feel free to make them!

**Comment by HaydenHildreth** [comment]
See v1.2.25.1011.g0348bea

http://repository.spotify.com/pool/non-free/s/spotify-client/

**Comment by sergiomb2** [comment]
we have a big problem, Fedora don't have  libayatana-appindicator3 
 
you can see this error on install of new spotify 

Problem: conflicting requests
- nothing provides libayatana-appindicator3.so.1()(64bit) needed by spotify-client-1.2.22.982-1.fc38.x86_64 from @commandline
(try to add '--skip-broken' to skip uninstallable packages)

**Comment by principis** [comment]
Working on it:

https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2253579
https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2253580
https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2253582

**Comment by sergiomb2** [comment]
Hi,

thank you for your work please see https://bugzilla.redhat.com/show_bug.cgi?id=1651349 , you will need provides and Obsolete old appindicator 

I also did some work on this https://copr.fedorainfracloud.org/coprs/sergiomb/libayatana-appindicator/

what is your fas username ?

**Comment by principis** [comment]
Thanks! I'll take a look.

fas username: principis

**Comment by doomsxday** [comment]
Hey @HaydenHildreth ,
I found a solution with [copr.fedorainfracloud.org](https://copr.fedorainfracloud.org/coprs/sergiomb/libayatana-appindicator) to install libayatana-appindicator3 on fedora :)

**Comment by HaydenHildreth** [comment]
> Hey @HaydenHildreth , I found a solution with [copr.fedorainfracloud.org](https://copr.fedorainfracloud.org/coprs/sergiomb/libayatana-appindicator) to install libayatana-appindicator3 on fedora :)

Awesome, thank you for that update! @sergiomb2 , should I close this PR? I see there is already a newer version that this PR/commit is using.

Thanks for you help on this guys, you're all awesome!

**Comment by sergiomb2** [comment]
we need add libayatana-appindicator to Fedora

**Comment by principis** [comment]
This will have to wait from side till February, sorry. It's a difficult package and I need proper time to understand the differences.

**Comment by sergiomb2** [comment]
yesterday, I updated https://copr.fedorainfracloud.org/coprs/sergiomb/libayatana-appindicator/ , I discarded ayatana-ido , and remove duplicates with old libappindicator, so no need to add provides and or obsoletes to old libappindicator.
My next step will be check yours package reviews ... 
Thank you

**Comment by sergiomb2** [comment]
I resumed things on https://bugzilla.rpmfusion.org/show_bug.cgi?id=6788

the workaround is `dnf copr enable sergiomb/libayatana-appindicator`

**Comment by principis** [comment]
libayatana-appindicator and friends are approved (thank you Sergio) and in testing. Please test if you have some free time.

[Fedora 38](https://bodhi.fedoraproject.org/updates/FEDORA-2024-8c5f8845cb)
[Fedora 39](https://bodhi.fedoraproject.org/updates/FEDORA-2024-ba8f8e7397)

```bash
dnf copr remove sergiomb/libayatana-appindicator
dnf remove libayatana-appindicator
# enable testing repo in links ^ and rebuild spotify
```

**Comment by sergiomb2** [comment]
Hi, @principis  we need also the new appindicator for epel9 and epel8  to build new lp-spotify there 

After the packages be on stable I may add Provides Obsoletes packages of the repo sergiomb/libayatana-appindicator

**Comment by principis** [comment]
> Hi, @principis we need also the new appindicator for epel9 and epel8 to build new lp-spotify there

Will do :)

**Comment by principis** [comment]
@sergiomb2 epel8 is not possible: https://github.com/AyatanaIndicators/ayatana-ido/blob/main/CMakeLists.txt#L47C1-L47C40
```
set(DEPS glib-2.0>=2.58 gtk+-3.0>=3.24)
```

**Comment by sergiomb2** [comment]
yes, I also drop epel8 builds, I checked now

**Comment by principis** [comment]
el9 update submitted: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2024-9e27048ebd

**Comment by sergiomb2** [comment]
ok this is finish,  we can close, I didn't because I haven't permissions 

Thank you

**Pull request closed without merging**
