### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by ldaneliukas**
Fixing readme as it stated that skype will be downloaded.

### CODE REVIEW

**Comment by sergiomb2** [comment]
merged thanks 
https://pkgs.rpmfusion.org/cgit/nonfree/lpf-spotify-client.git/commit/?id=77244836286d2be7733f3eb4d12e672c6c1a34dd

**Comment by szaszm** [comment]
What is the relationship between GitHub and pkgs.rpmfusion.org/git? GitHub master is not updated with this pull request. (2 commits behind at the moment)

**Comment by sergiomb2** [comment]
sometimes github mirror doesn't update , in next push (commit) should be updated .

**Comment by sergiomb2** [comment]
the commit is now here: https://github.com/rpmfusion/lpf-spotify-client/commit/77244836286d2be7733f3eb4d12e672c6c1a34dd .

Thanks for the pull request

**Pull request closed without merging**
