### PR TITLE
feat: add actions to check new versions

### PR DESCRIPTION
**Pull request by vmaerten**
Following this comment : https://github.com/rpmfusion/lpf-spotify-client/pull/19#issuecomment-2088636128

If you want you can merge this PR or copy / paste the code as you wish. You may want adjust the cron.
The workflow_dispatch let you run it from the UI.

You need to allow Github Action to create PR. In settings/actions/general : 

image

### CODE REVIEW

**Comment by kwizart** [comment]
We don't merge/approve via github (only a read-only), so it won't work.

Also the check_new_version.py doesn't work with current fedora for me.
```
./check_new_version.py                                                                                                     master 
/media/nvme/sources/rpmfusion/lpf-spotify-client/./check_new_version.py:32: SyntaxWarning: invalid escape sequence '\d'
  regexp = re.compile('spotify-client_(\d{1,2}[.]\d{1,2}[.]\d{1,3}[.]\d{1,3})([.].*)')
Traceback (most recent call last):
  File "/media/nvme/sources/rpmfusion/lpf-spotify-client/./check_new_version.py", line 34, in <module>
    (version64, minor64) = regexp.findall(deb64)[0]
                           ~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

```
So it's unlikely to work with fedora:40's  python3.

**Comment by sergiomb2** [comment]
hey wait

**Comment by sergiomb2** [comment]
is working with this commit:  https://github.com/rpmfusion/lpf-spotify-client/commit/ee9115f9c6b3cf8954cd78cc9d559afb36abd752

I asked for a way to notify a new release , like release-monitor of Fedora and this if give me one notification in email would be enough , I will take care of the rest .

Thank you

**Comment by kwizart** [comment]
Then, just create whatever github repository you need to debug/verify and create a dedicated tests, but don't use the package for this.

**Comment by sergiomb2** [comment]
done https://github.com/sergiomb2/lpf-spotify-client/pull/1 

Thank you @vmaerten , with last push master branch is updated now

**Comment by sergiomb2** [comment]
@vmaerten it works https://github.com/sergiomb2/lpf-spotify-client/pull/2 thank you

**Pull request closed without merging**
