### PR TITLE
Update to 1.0.45-2

### PR DESCRIPTION
**Pull request by wieczorek1990**

### CODE REVIEW

**Comment by kwizart** [comment]
Thx for your PR,
Can you consider to maintain this package directly from our infra ?
http://rpmfusion.org/Contributors

**Comment by wieczorek1990** [comment]
Will try to check it out later.

**Comment by sergiomb2** [comment]
Hi I miss this PR , it may close now, Thanks.

**Comment by sergiomb2** [comment]
Hi, 
I made this script , https://github.com/rpmfusion/lpf-spotify-client/blob/master/check_new_version.py 
spotify is now updated .
you may close the pull request (I don't have permissions) 

Thanks.

**Pull request closed without merging**
